spring.application.name=workinsight
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/workinsight
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

ocr.enabled=true
ocr.tesseract.language=eng
ocr.max-pages=3


ai.openai.api-key=${AI_OPENAI_API_KEY:}
ai.openai.base-url=https://api.openai.com/v1
ai.openai.text-model=gpt-4o-mini
ai.openai.vision-model=gpt-4o-mini


geocoding.nominatim.enabled=true

jwt.secret=change-this-secret-key-change-this-secret-key
jwt.expiration-seconds=3600

app.frontend-base-url=http://localhost:4200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
