spring.application.name=workinsight
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/workinsight}
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
